name: Linux x86

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build-debug:
    name: Build Debug
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: repository
          submodules: recursive

      - name: Clean submodules (Local)
        run: |
          cd repository
          # Clean untracked files inside submodules
          git submodule foreach --recursive git reset --hard
          git submodule foreach --recursive git clean -fdx
          git submodule sync --recursive
          git submodule update --init --force --recursive

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y build-essential zip unzip curl cmake pkg-config git gcc-multilib g++-multilib
          sudo apt-get install -y uuid-dev

      - name: Install Premake5
        run: |
          git clone --depth=1 https://github.com/premake/premake-core.git || true
          cd premake-core
          make -f Bootstrap.mak linux
          mv ./bin/release/premake5 ../repository
          cd ..

      - name: Initialize Premake
        run: |
          cd repository
          ./premake5 gmake
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg

      - name: Build Dependency
        run: |
          cd repository/sdk32/projects/linux/gmake
          make -f common.make config=debug_x86
          make -f LZMA.make config=debug_x86
          make -f tier1.make config=debug_x86
          cd ../../../../..

      - name: Build
        run: |
          cd repository/build
          make -f plugin_ljpatch32.make config=debug_x86
          cd ../..

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug_x86_linux
          path: repository/bin/x86/Debug/*
          if-no-files-found: warn

  build-release:
    name: Build Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: repository
          submodules: recursive

      - name: Clean submodules (Local)
        run: |
          cd repository
          # Clean untracked files inside submodules
          git submodule foreach --recursive git reset --hard
          git submodule foreach --recursive git clean -fdx
          git submodule sync --recursive
          git submodule update --init --force --recursive

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y build-essential zip unzip curl cmake pkg-config git gcc-multilib g++-multilib
          sudo apt-get install -y uuid-dev

      - name: Install Premake5
        run: |
          git clone --depth=1 https://github.com/premake/premake-core.git || true
          cd premake-core
          make -f Bootstrap.mak linux
          mv ./bin/release/premake5 ../repository
          cd ..

      - name: Initialize Premake
        run: |
          cd repository
          ./premake5 gmake
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg

      - name: Build Dependency
        run: |
          cd repository/sdk32/projects/linux/gmake
          make -f common.make config=release_x86
          make -f LZMA.make config=release_x86
          make -f tier1.make config=release_x86
          cd ../../../../..

      - name: Build Release
        run: |
          cd repository/build
          make -f plugin_ljpatch32.make config=release_x86
          cd ../..

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release_x86_linux
          path: repository/bin/x86/Release/*
          if-no-files-found: warn